name: first-workflow
on:
  workflow_dispatch:
  inputs:
    nammVersion:
      description: 'Namm version'
      required: true
      default: '1.0.0'
jobs:
  first-workflow:
    name: first-workflow
    runs-on: ubuntu-latest
    steps:
      - name: show now
        run: echo "now is $(date)"
        
