name: first-workflow
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to run'
        required: true
        type: string
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
jobs:
  first-workflow-job:
     name: first job
     runs-on: ubuntu-latest
     steps:
       - name: run bash command
         run: ls      
         shell: bash
       - name: checkout code
         uses: actions/checkout@v4
       - name: after checkout
         run: ls
         shell: bash    
