name: first-workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "This job is running every 5 minutes"
      - name: List files in the repository
        run: ls -Ra  